### ISSUE TITLE
Animate player sprite

### ISSUE THREAD

**Issue by CheeseLord** [CheeseLord/plaid#24]
The player looks silly without animation.  Tutorial [here](http://gigi.nullneuron.net/gigilabs/animations-with-sprite-sheets-in-sdl2/).

**Comment by kronmillerg** [comment]
Idea for how to keep track of animation progress: have a single global counter, and animations can all be based on how many "animation ticks" have passed. For now at least, let's increment it in the main loop; we can clean that up once we figure out how observers are supposed to work. The animation counter should be an integer, and I recommend making one animation tick 1/60 seconds (because it's divisible by 1..6).

Also, I recommend manually resetting the counter once it gets high enough, rather than just letting it wrap at 2^31. Probably every second or every 60 seconds is good.

**Comment by CheeseLord** [comment]
The player is now animated at random.  We still need to track animation progress.
