### ISSUE TITLE
Platforms should have sprites

### ISSUE THREAD

**Issue by CheeseLord** [CheeseLord/plaid#26]

**Comment by kronmillerg** [comment]
We probably want to create a single (square?) image and then just tile it to draw platforms, rather than trying to scale an image when platforms could vary in width:height ratio.

**Comment by kronmillerg** [comment]
Image added. Since platforms vary in both height and width, we can't just look at a platform's size to figure out what to scale the image by. Also, scaling the image will probably produce annoying effects (either aliasing or blurring). So let's just use the sprite image in its original size, tiled and cropped to the size of the platforms.
